/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package jgame23;

import org.junit.Test;
import static org.junit.Assert.*;

public class BattleOfMidwayTest {
    @Test public void appHasAGreeting() {
        BattleOfMidway classUnderTest = new BattleOfMidway();
       // assertNotNull("app should have a greeting", classUnderTest.getGreeting());
    }
}
